version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs_db
    ports:
      - '5432:5432'
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
